# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diagnosis_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "diagnosis_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17\x64iagnosis_service.proto"8\n\x15\x44iagnosisQueryRequest\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t"\x1d\n\x1b\x45mptyDiagnosisQueryResponse2a\n\x10\x44iagnosisService\x12M\n\x15\x45nqueueDiagnosisQuery\x12\x16.DiagnosisQueryRequest\x1a\x1c.EmptyDiagnosisQueryResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "diagnosis_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DIAGNOSISQUERYREQUEST"]._serialized_start = 27
    _globals["_DIAGNOSISQUERYREQUEST"]._serialized_end = 83
    _globals["_EMPTYDIAGNOSISQUERYRESPONSE"]._serialized_start = 85
    _globals["_EMPTYDIAGNOSISQUERYRESPONSE"]._serialized_end = 114
    _globals["_DIAGNOSISSERVICE"]._serialized_start = 116
    _globals["_DIAGNOSISSERVICE"]._serialized_end = 213
# @@protoc_insertion_point(module_scope)
