name: Staged CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Run Composite Action to Install Packages
      uses: ./.github/actions

    - name: Run Trivy Composite Action
      uses: ./.github/actions/trivys
      with:
          TRIVYS_SECRET: ${{ secrets.TRIVYS }}
          TRIVYS_PAT: ${{ secrets.trivys_pat }}

    - name: Run tests
      run: make test

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Run Composite Action to Install Packages
        uses: ./.github/actions

      - name: Run Pre-commit
        run: |
          if [ -f "poetry.lock" ]; then echo "running poetry lock" && poetry lock; fi;
          poetry install --no-root --all-extras
          poetry run pre-commit run --all-files;
